-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
vim.api.nvim_set_hl(0, "LineNr", { bg = "none", fg = "#5c6370" })
vim.api.nvim_set_hl(0, "SignColumn", { bg = "none" })
vim.api.nvim_set_hl(0, "AlphaHeader", { fg = "#957FB8" })
vim.api.nvim_set_hl(0, "AlphaButtons", { fg = "#7AA89F" })
vim.api.nvim_set_hl(0, "AlphaShortcut", { fg = "#E6C384" })
vim.api.nvim_set_hl(0, "AlphaFooter", { fg = "#8a8780" })
