set -ga terminal-overrides ",screen-256color*:Tc"
set -g default-terminal "screen-256color"
set -s escape-time 0

unbind l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

unbind p
bind -r i previous-window
unbind n
bind -r o next-window


unbind %
bind = split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"
